### ISSUE TITLE
Code injection vulnerability on /system/log endpoint

### ISSUE THREAD

**Issue by pondzikk** [PiBrewing/craftbeerpi4#132]
URL GET parameter `{logtime}` utilized within the [downloadlog](https://github.com/PiBrewing/craftbeerpi4/blob/1f645a835c32fc0133c14fbbeead41f55a387465/cbpi/controller/system_controller.py#L67) function from /cbpi/controller/system_controller.py  is subsequently passed to the [os.system](https://github.com/PiBrewing/craftbeerpi4/blob/1f645a835c32fc0133c14fbbeead41f55a387465/cbpi/controller/system_controller.py#L84) function in /cbpi/http_endpoints/http_system.py  without prior validation allowing to execute arbitrary code.

Vulnerability exists from `4.0.0.58` version (`563fae9` commit)

**Comment by avollkopf** [comment]
Unfortunately, I am not an expert nor a professional programmer. I need to look into it and read more details on the topic. Are you referring to changes documented [here](https://semgrep.dev/docs/cheat-sheets/python-command-injection/)? Or even better, do you have a proposal on how to fix it with a PR?

Anyhow, it'll take some time.

**Comment by pondzikk** [comment]
Yes, mentioned mitigations should fix this issue, if i find any free time soon i will test mitigation and make PR.

**Comment by avollkopf** [comment]
@pondzikk Would a check, if logtime is an integer and below a certain value reduce the risk significantly? This could be a short time solution.

**Comment by avollkopf** [comment]
@pondzikk please check if quick solution would work as start. Only integer values and a 'b' are now forwarded to the system controller.

**Comment by pondzikk** [comment]
I haven't checked it in action, but after reading changes i think it would fix this issue.

**Comment by CERT-PL-CNA** [comment]
@avollkopf
we have been requested to assign a CVE for that vulnerability.
We have reserved CVE-2024-3955 and we will soon publish its details.
If you want to consult its content please contact us at our email address.

Best regards
CERT.PL CNA

**Comment by avollkopf** [comment]
Added [test branch](https://github.com/PiBrewing/craftbeerpi4/commit/f5c242d7c856e8f7be2cac8e8ca4dcb51d779515) that is using systemd-python package instead of os.system to read from journal. Tests start5ed, but reading from log is working already and issue should be solved with the usage of the additional package

**Comment by avollkopf** [comment]
Added [test branch](https://github.com/PiBrewing/craftbeerpi4/commit/f5c242d7c856e8f7be2cac8e8ca4dcb51d779515) that is using systemd-python package instead of os.system to read from journal. Tests start5ed, but reading from log is working already and issue should be solved with the usage of the additional package

**Comment by CERT-PL-CNA** [comment]
The vulnerability was described and published at the following addresses:
https://www.cve.org/CVERecord?id=CVE-2024-3955
https://cert.pl/en/posts/2024/05/CVE-2024-3955/

Best regards
CERT.PL CNA

**Comment by avollkopf** [comment]
Closed with aforementioned PR
